version: '3.8'

services:
  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${GATEWAY_PORT}
      - USERS_SERVICE_URL=http://service_users:${USERS_PORT}
      - ORDERS_SERVICE_URL=http://service_orders:${ORDERS_PORT}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network
    depends_on:
      - service_users
      - service_orders

  service_users:
    build: ./service_users
    container_name: service_users
    ports:
      - "${USERS_PORT}:${USERS_PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${USERS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=1h
      - DB_HOST=postgres
      - DB_PORT=${POSTGRES_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    networks:
      - app-network
    depends_on:
      - postgres

  service_orders:
    build: ./service_orders
    container_name: service_orders
    ports:
      - "${ORDERS_PORT}:${ORDERS_PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${ORDERS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=postgres
      - DB_PORT=${POSTGRES_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: postgres_systemcontrol
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
