version: '3.8'

services:
  api_gateway:
    environment:
      - NODE_ENV=development
    volumes:
      - ./api_gateway:/usr/src/app
      - /usr/src/app/node_modules

  service_users:
    environment:
      - NODE_ENV=development
    volumes:
      - ./service_users:/usr/src/app
      - /usr/src/app/node_modules

  service_orders:
    environment:
      - NODE_ENV=development
    volumes:
      - ./service_orders:/usr/src/app
      - /usr/src/app/node_modules
